version: '3.7'

services:
  oathkeeper:
    image: oryd/oathkeeper:v0.40
    depends_on:
      - kratos
      - keto
    ports:
      - 4455:4455
      - 4456:4456
    command:
      serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
      - AUTHORIZER_KETO_URL=http://keto:4466
    restart: on-failure
    volumes:
      - ./config:/etc/config/oathkeeper
    networks:
      - shared_network

networks:
  shared_network:
    external: true
volumes:
  kratos-sqlite:
