FROM oryd/oathkeeper:v0.40

USER root

COPY ./config /etc/config/oathkeeper
COPY entrypoing-admin.sh /usr/local/bin/entrypoing.sh

RUN chmod +x /usr/local/bin/entrypoint.sh

USER ory

EXPOSE 4456
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]